/**
 * Decalre all the strings here for using in throughout the app.
 */
export const Strings = {
  noInternet: 'You are offline. Please check your internet connection',
  backOnline: 'You are back online',
  noInternetConnection: 'No internet connection.',
  somethingPleaseTryAgain: 'Some error occured please try again',
  pleaseTryAgain: 'Please try again after some time.',
  internalServer: 'Internal Server Error',
  noData: 'Not found',
  email: 'Email Address',
  emailEnter: 'Enter your email address',
  name: 'Name',
  mobileNumber: 'Mobile Number',
  mobileNumberEnter: 'Enter your Mobile Number',
  password: 'Password',
  passwordEnter: 'Enter your password',
  confirmPassword: 'Confirm Password',
  signup: 'Sign up',
  signIn: 'Sign In',
  login: 'Login',
  countryCode: '+91',
  loggedOutSuccessfully: 'Logged out Successfully!',
  dealerEntry: 'Dealer Entry',
  dealerVisit: 'Dealer Visit',
  sessionExpired: 'Session expired! Please login again',
  notification: 'Notification',
  pleaseWait: 'Please wait...',
  noDataFound: 'No data found...',
  appUpdateDesc: `Update to the latest version to continue using `,
  appUpdateTitle: 'Keep up-to-date',
  updateLater: 'Update Later',
  updateNow: 'Update Now',
  noInternet: 'You are offline. Please check your internet connection',
  backOnline: 'You are back online',
  noInternetConnection: 'No internet connection.',
  somethingPleaseTryAgain: 'Some error occured please try again',
  pleaseTryAgain: 'Please try again after some time.',
  internalServer: 'Internal Server Error',
  noData: 'Not found',
  forgotPwdTitle: 'Forgot Password?',
  forgotPwdSubTitle: 'Please enter your email id to reset your \n password.',
  sendVerifiCode: 'Send Verification Code',
  email: 'Email Address',
  emailEnter: 'Enter your email address',
  name: 'Name',
  mobileNumber: 'Mobile Number',
  mobileNumberEnter: 'Enter your Mobile Number',
  password: 'Password',
  passwordEnter: 'Enter your password',
  confirmPassword: 'Confirm Password',
  signup: 'Sign up',
  alreadyhaveAnAccount: 'Already have an account?',
  continueWith:
    'Continue with your email id to get started with your loan application.',
  continueWithMob:
    'Continue with your Mobile Number to get started with your loan application. ',
  // yourApplication: 'your loan application.',
  letsGet: `Let's get started`,
  signIn: 'Sign In',
  login: 'Login',
  countryCode: '+91',
  createAccount: 'Create account?',
  doNotHaveAccount: 'Dont have an account?',
  verifyBankStatement: 'Verify Bank Statement',
  uploading: 'Uploading',
  offering: 'Offering',
  settings: 'Settings',
  continue: 'Continue',
  yourLimitAndSpent: 'Your Limit & Spent',
  payNow: 'Pay Now',
  dueDate: 'One less due date to remember!',
  autoPlayNetBanking: 'Autopay your bill throught net banking OR UPI,',
  knowMore: 'Know More',
  availableLimit: 'Available Limit',
  spendTillNow: 'Spend till now',
  hello: 'Hello',
  enableAutoPay: 'Enable Autopay',
  recentTransactions: 'Recent Transactions',
  viewAll: 'View All',
  submit: 'Submit',
  //permissions
  weNeed: 'We need Some \n permission to access \n your...',
  location: 'Location',
  sms: 'SMS',
  contacts: 'Contacts',
  cameraMedia: ' Camera & Media Access',
  device: 'Device Information',
  locationDetailTo: ' To verify your address',
  locationDetails: 'details',
  smsDetailTo: ' To understand your income & ',
  smsDetailSpend: 'spend patterns for deciding your',
  smsDetailCredit: 'credit limit',
  contactsDetailTo: ' To verify your device ',
  contactsDetailInfo: 'information',
  cameraDetailTo: ' To add',
  cameraDetailsPhotos: 'photos of required documents',
  deviceDetailTo: ' To link your ',
  deviceDetailsPhone: 'phone to your account',
  verifyAccount: 'Verify Account',
  pleaseShare:
    'Please share your account details for transaction verification, loan disbursement and EMI deduction.',
  selectBank: 'Select Bank',
  ifscCode: 'IFSC Code',
  ifscCodeP: 'Enter IFSC Code',
  accountNumber: 'Account Number',
  accountNumberP: 'Enter Account Number',
  confirmAccount: 'Confirm Account Number.',
  confirmAccountP: 'Enter to confirm account no.',
  GetLoanoffer: 'Get Loan offer',
  SelectEmpType: 'Select Your Employment Type',
  PleaseFillThe:
    'Please Fill the following Information Correctly We will use it to provide the best loan offer ',
  Salaried: 'Salaried',
  SelfEmployed: 'Self Employed',
  EnterUserName: 'Enter user name',
  DateOfBirth: 'Date of Birth',
  DDMMYY: 'DD-MM-YY',
  EnterPanNumber: 'Enter pan number',
  PANNumber: 'PAN Number',
  EnterAddress: 'Enter address',
  Address: 'Address',
  SelectGender: 'Select Gender',
  EnterEmailId: 'Enter email id',
  PersonalEmailId: 'Personal Email Id',
  CompanyEmailId: 'Company Email Id',
  EnterCompanyName: 'Enter Company Name',
  CompanyName: 'Company Name',
  HowYouReceive: 'How you receive your salary ?',
  PersonalInformation: 'Personal Information',
  Male: 'Male',
  Female: 'Female',
  Cash: 'Cash',
  Cheque: 'Cheque',
  Online: 'Online',
  ConfirmContinue: 'Confirm & Continue',
  ReUpload: 'Re-upload',
  uploadProgress: '% upload progress',
  EnsureTakingPhoto: 'Ensure You Are Taking Clear Photo Of Original Documents.',
  UploadDocuments: 'Upload Documents',
  AddressProof: 'Address Proof',
  PanCard: 'Pan Card',
  YourPhoto: 'Your Photo',
  Camera: 'Open Camera',
  Gallery: 'Select From Gallery',
  UploadManually: 'Upload Manually',
  UploadNetBanking: 'Upload Using Net Banking',
  SendByMail: 'Send By Mail',
  WeNeedBankStatement:
    'We need your bank statement to verify your income. Choose how you do like to upload them',
  WeProcessingStatement:
    'We are processing your statement to get the best offer for you.',
  ItMinutes: 'It can take 2 minutes.',
  OfferConfirmation: `Offer \n Confirmation`,
  UploadYourBankStatements:
    'Upload your bank statements to get a confirmed offer of up to',
  Faq: 'Faq',
  whoAre: 'Who we are',
  aboutZuluPay: 'About ZuluPay',
  about_msg:
    'By accessing our app. Zulu pay App. you are agreeing to be bound by these terms of service, all applicable lows and regulations, and agree that you are responsible for compliance with any application local laws.',
  zuluPayUser: 'ZuluPay \n User',
  yearsExperiences: 'Years \n Experiences',
  revenueGrowth: 'Revenue \n Growth',
  quotes:
    'I agree that the opening and maintenance of the account is subject to rules and regulations introduced.',
  authorName: 'jean-phillppe Nuel, Founder',
  chooseYourLanguage: 'Choose Your \n Language',
  otpVerification: 'OTP Verification',
  enterFourDigitOtp: 'Please enter 4 digits code sent to Your\nMobile Number',
  mobileExample: 'Mobile Number +6190022****',
  didntReceiveOtp: 'Didnt Receive OTP?',
  resent: 'Resend',
  TermsAndCondition: 'Terms And Condition',
  Archive: 'Archive',
  FlexibleAmount: 'Flexible Amount',
  //
  GetLoanAnywhere: 'Get a loan from anywhere between',
  KtoLac: '10k to 5Lac',
  QuickDisbursal: 'Quick Disbursal',
  MoneyInBank: 'Money in your bank account in just a',
  fewHours: 'few hours',
  ConvenientProcess: 'Convenient process',
  PaybackYourEMI: 'Payback Your EMI Through the app',
  gender: 'Gender',
  Phone: 'Phone',
  SaveContinue: 'Save & Continue',
  Profile: 'Profile',
  ReferEarn: 'Refer and Earn',
  ChooseLanguage: 'Choose Language',
  PERSONAL: 'PERSONAL',
  SUPPORT_FEEDBACK: 'SUPPORT AND FEEDBACK',
  ABOUT: 'ABOUT',
  Zulupay: 'Zulupay',
  SignOut: 'Sign Out',
  applicationSubmitted: 'Application Submitted',
  loanVerificationSubmitted: 'Loan Verification Submitted',
  loanDescriptionLabel:
    'The above steps generally take about 1 working day if all documents are correct.',
  loanSecDescriptionLabel:
    'You will be informed about the status of your application at every step.',
  PersonalInfo: 'Personal info',
  Documents: 'Documents',
  selectAmount: 'Select Amount',
  monthlyEMI: 'Monthly EMI',
  principalAmount: 'Principal Amount',
  interestAmount: 'Interest Amount',
  totalPayble: 'Total Payble',
  viewDetails: 'View details',
  loanAmount: 'Loan Amount',
  tenureMonth: 'Tenure (Month)',
  confirm: 'Confirm',
  rupeeSymbol: '₹',
  settingsChanged: 'Your language preference can be changed \n at any time in',
  validMobileNumber: 'Please enter a valid mobile number',
  selectSalaried: 'Select Salaried',
  sorry: 'Sorry',
  notProvidingLoan: 'Right now we are not providing loans to self-employed.',
  enterFullName: 'Please enter your full name',
  fileName: 'File Name -',
  //
  pleaseEnterEmail: 'Please enter email Id',
  validEmailFormat: 'Please enter a valid email Id',
  enterPassword: 'Please enter password',
  enterOldPassword: 'Please enter old password',
  enterNewPassword: 'Please enter new password',
  passwordContainEightChar:
    'Password must contain atleast 8 characters, 1 special character, 1 uppercase & 1 number',
  enterConfirmPassword: 'Please enter confirm password',
  confirmPasswordAndPassword: 'Confirm Password and Password does not match',
  newPassAndConfirmPass: 'New password and confirm password does not match',
  pleaseEnterConfirmPass: 'Please enter confirm new password',
  emailId: 'Email ID',
  pleaseEnterValidName: 'Please enter valid name',
  lessThanTwentyChar: 'Please enter less than 20 characters',
  enterMobileNumber: 'Please enter mobile number',
  mobileShouldBe: 'Mobile number should  be start with 6,7,8,9',
  verifyCode: 'Verify Code',
  enterOTP: 'Please enter OTP',
  fourDigitValidOTP: 'Please enter 4 digit valid OTP',
  pleaseEnterIFSCCode: 'Please enter IFSC Code',
  validIFSCCode: 'Please enter valid IFSC Code',
  pleaseEnterAccountNumber: 'Please enter Account Number',
  accConfirm: 'Confirm Account and Account does not match',
  enterValidAccountNumber: 'Please enter Valid Account Number',
  pleaseSelectBank: 'Please Select Bank',
  pleaseSelectDateOfBirth: 'Please select date of birth',
  pleaseEnterValidPanNumber: 'Please enter valid PAN number',
  pleaseEnterCompanyName: 'Please enter company name',
  pleaseSelectAddress: 'Please enter Address',
  recent: 'Recent',
  thisWeek: 'This Week',
  month: 'Month',
  TotalOutstanding: 'Total Outstanding Loan Amount',
  LoanStatus: 'Loan Status',
  rs: 'RS.',
  EMIPaid: `EMI's Paid`,
  Due_Date: 'Due Date',
  BenefitFromHigh: 'Benefit from a high Loan To Value ratio',
  ApplyForLoan: 'Apply For Loan',

  //otp validation
  validOneTimeLength: 'Please enter 4 digit valid OTP',
  validOneTimePassword: 'Please enter OTP',
};
export default Strings;
